name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # run tests in the client subdir
      - run: docker build -t betasoftcologne/multi-docker -f ./client/Dockerfile.dev ./client
      # try "-- --coverage" if -e CI=true does not work 
      - run: docker run -e CI=true betasoftcologne/multi-docker npm test
 
      # build production images
      - run: docker build -t betasoftcologne/multi-client ./
      - run: docker build -t betasoftcologne/multi-nginx ./nginx
      - run: docker build -t betasoftcologne/multi-server ./server
      - run: docker build -t betasoftcologne/multi-worker ./worker
 
      # push images to dockerhub
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker push betasoftcologne/multi-client
      - run: docker push betasoftcologne/multi-nginx
      - run: docker push betasoftcologne/multi-server
      - run: docker push betasoftcologne/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
# TODO      - name: Deploy to Elastic Beanstalk
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: docker-react
#          environment_name: Docker-react-env
#          existing_bucket_name: elasticbeanstalk-us-east-1-361741102217
#          region: us-east-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
