name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker build -t betasoftcologne/multi-docker -f ./Dockerfile.dev ./
      - run: docker run -e CI=true betasoftcologne/multi-docker npm test
 
      - run: docker build -t betasoftcologne/multi-client-10-14 ./
      - run: docker build -t betasoftcologne/multi-nginx-10-14 ./nginx
      - run: docker build -t betasoftcologne/multi-server-10-14 ./server
      - run: docker build -t betasoftcologne/multi-worker-10-14 ./worker
 
      - run: docker push betasoftcologne/multi-client-10-14
      - run: docker push betasoftcologne/multi-nginx-10-14
      - run: docker push betasoftcologne/multi-server-10-14
      - run: docker push betasoftcologne/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
# TODO      - name: Deploy to Elastic Beanstalk
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: docker-react
#          environment_name: Docker-react-env
#          existing_bucket_name: elasticbeanstalk-us-east-1-361741102217
#          region: us-east-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
